name: CI/CD

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  TESTCOVER_THRESHOLD: 80
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18

      - name: run go test
        run: go test -coverprofile=cov.out -covermode=atomic

      - name: Check test coverage is above treshold
        run: |
          echo "Threshold             : $TESTCOVER_THRESHOLD %"
          totalCoverage=`go tool cover -func=cov.out | grep -E '^total:\s+' | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          if (( $(echo "$totalCoverage $TESTCOVER_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Failed: Current test coverage is below the threshold."
              exit 1
          fi

  golangci:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest